name: Daily WinScoreAI Runner

on:
  schedule:
    - cron: '0 2 * * *'  # เวลา 09:00 ไทย (UTC+7 → UTC+2)
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    env:
      FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run WinScoreAI System
        run: python daily_runner.py
