name: CI Smoke API-Football

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FB_METRICS_PATH: ""                # ปิดเขียน metrics ในรอบทดสอบ
      FB_CONTINUE_ON_ERROR: "true"
      FB_UPDATE_CHUNK_SIZE: "800"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r winscoreai-auto-github/API-Football-auto/requirements.txt

      # (ข้าม import เป็นโมดูล เพราะชื่อโฟลเดอร์มีเครื่องหมายขีด)

      - name: Fetch tiny odds window (today only)
        working-directory: winscoreai-auto-github/API-Football-auto
        run: |
          python scripts/af_today_odds.py --days 1 --allow allowlist_A.txt --bookmaker 6 --outdir live_odds

      - name: Patch odds (dry-run)
        working-directory: winscoreai-auto-github/API-Football-auto
        run: |
          JSON=$(ls -t live_odds/odds_full_*.json | head -n1)
          echo "Using $JSON"
          python scripts/patch_odds.py --json "$JSON" --dry-run

      - name: Fetch finished results (yesterday only)
        working-directory: winscoreai-auto-github/API-Football-auto
        run: |
          YEST=$(date -u -d "yesterday" +%F)
          python scripts/af_results.py --date_from $YEST --date_to $YEST --allow allowlist_A.txt --outdir data

      - name: Patch results + xG (dry-run)
        working-directory: winscoreai-auto-github/API-Football-auto
        run: |
          RES=$(ls -t data/results_full_*.json | head -n1)
          echo "Using $RES"
          python scripts/patch_result.py --json "$RES" --dry-run
