name: CI Smoke

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      # fb_client tuning for test
      FB_METRICS_PATH: ""                # ปิดเขียน metrics ใน smoke
      FB_CONTINUE_ON_ERROR: "true"
      FB_UPDATE_CHUNK_SIZE: "800"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r API-Football/requirements.txt

      - name: Verify secrets exist
        run: |
          test -n "$API_FOOTBALL_KEY" || (echo "Missing API_FOOTBALL_KEY" && exit 1)
          test -n "$FIREBASE_CREDENTIALS" || (echo "Missing FIREBASE_CREDENTIALS" && exit 1)
          test -n "$FIREBASE_DATABASE_URL" || (echo "Missing FIREBASE_DATABASE_URL" && exit 1)

      - name: Import scripts (syntax check)
        run: |
          python - <<'PY'
          import importlib, sys
          mods = [
            "API-Football.scripts.common_env",
            "API-Football.scripts.fb_client",
            "API-Football.scripts.af_today_odds",
            "API-Football.scripts.patch_odds",
            "API-Football.scripts.af_results",
            "API-Football.scripts.patch_result",
          ]
          for m in mods:
              importlib.import_module(m)
              print("ok:", m)
          PY

      - name: Fetch tiny odds window (today only)
        working-directory: API-Football
        run: |
          python scripts/af_today_odds.py --days 1 --allow allowlist_A.txt --bookmaker 6 --outdir live_odds

      - name: Patch odds (dry-run)
        working-directory: API-Football
        run: |
          JSON=$(ls -t live_odds/odds_full_*.json | head -n1)
          echo "Using $JSON"
          python scripts/patch_odds.py --json "$JSON" --dry-run

      - name: Fetch finished results (yesterday only)
        working-directory: API-Football
        run: |
          YEST=$(date -u -d "yesterday" +%F)
          python scripts/af_results.py --date_from $YEST --date_to $YEST --allow allowlist_A.txt --outdir data

      - name: Patch results + xG (dry-run)
        working-directory: API-Football
        run: |
          RES=$(ls -t data/results_full_*.json | head -n1)
          echo "Using $RES"
          python scripts/patch_result.py --json "$RES" --dry-run
