# .github/workflows/daily-odds.yml
name: daily-odds

on:
  schedule:
    - cron: "*/30 6-22 * * *"   # ทุก 30 นาที ช่วงก่อนแข่ง (UTC)
  workflow_dispatch:

# โฟลเดอร์งานของ API-Football-auto
defaults:
  run:
    working-directory: winscoreai-auto-github/API-Football-auto

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ดึง odds ช่วงวันนี้+พรุ่งนี้ (กันหลุด timezone)
      - name: Pull odds JSON
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_VENDOR: ${{ secrets.API_FOOTBALL_VENDOR }}
        run: |
          TODAY=$(date -u +%F)
          python scripts/af_today_odds.py \
           --days 2 \
           --allow allowlist_ALL.txt \
           --outdir live_odds



      - name: Debug list live_odds
        run: ls -lah live_odds || true
            print("Raw fixtures fetched:", len(fixtures))
            print("Sample:", fixtures[:3])

      # เขียนเข้า Firebase เฉพาะเมื่อมีไฟล์ JSON จริง
      - name: Patch odds → Firebase
        if: ${{ hashFiles('winscoreai-auto-github/API-Football-auto/live_odds/odds_full_*.json') != '' }}
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          LATEST=$(ls -1t live_odds/odds_full_*.json | head -n1)
          echo "inWhld: $LATEST"
          python scripts/patch_odds.py --json "$LATEST"

      # เก็บผลลัพธ์เป็น artifact (ถ้าไม่มีไฟล์ก็แค่เตือน ไม่ fail)
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: odds-json
          path: live_odds/odds_full_*.json
          if-no-files-found: warn

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: odds-csv
          path: live_odds/odds_flat_all_*.csv
          if-no-files-found: warn






