# .github/workflows/daily-odds.yml
name: daily-odds

on:
  schedule:
    # ทุก 30 นาที ช่วง 6-22 UTC (ปรับได้ตามต้องการ)
    - cron: "*/30 6-22 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: winscoreai-auto-github/API-Football-auto

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 1) ดึง odds วันนี้+พรุ่งนี้ (UTC) → สร้าง JSON/CSV
      - name: Pull odds JSON/CSV
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_VENDOR: ${{ secrets.API_FOOTBALL_VENDOR }}
        run: |
          echo "=== pull odds (today+tomorrow, UTC) ==="
          python scripts/af_today_odds.py \
            --days 2 \
            --allow allowlist_ALL.txt \
            --outdir live_odds

      # 2) ดูไฟล์ที่ได้ + preview หัว JSON (ช่วย debug)
      - name: Debug list live_odds
        run: |
          echo "---- live_odds/ ----"
          ls -lah live_odds || true

          LATEST_JSON="$(ls -1t live_odds/odds_full_*.json 2>/dev/null | head -n1 || true)"
          echo "LATEST_JSON=${LATEST_JSON}"

          if [[ -n "${LATEST_JSON}" && -f "${LATEST_JSON}" ]]; then
            echo "---- preview first 2000 chars ----"
            head -c 2000 "${LATEST_JSON}" || true
          fi

      # 3) Patch เข้า Firebase (ข้ามอัตโนมัติถ้าไม่พบไฟล์)
      - name: Patch odds → Firebase
        if: ${{ always() }}
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          set -e
          LATEST_JSON="$(ls -1t live_odds/odds_full_*.json 2>/dev/null | head -n1 || true)"
          echo "LATEST=${LATEST_JSON}"
          if [[ -n "${LATEST_JSON}" && -f "${LATEST_JSON}" ]]; then
            python scripts/patch_odds.py --json "${LATEST_JSON}"
          else
            echo "no odds_full_*.json → skip patch"
          fi

      # (เลือกได้) เก็บ artifacts ไว้โหลดจากหน้า Actions
      - name: Upload JSON artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odds-json
          path: live_odds/odds_full_*.json
          if-no-files-found: warn

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odds-csv
          path: live_odds/odds_flat_all_*.csv
          if-no-files-found: warn
