# .github/workflows/daily-odds.yml
name: daily-odds
on:
  schedule: [{ cron: "*/30 6-22 * * *" }]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: winscoreai-auto-github/API-Football-auto   # <<< ชี้ไปที่โฟลเดอร์จริง
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull odds JSON
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_VENDOR: ${{ secrets.API_FOOTBALL_VENDOR }}
        run: |
          python API-Football-auto/scripts/af_today_odds.py \
          --days 1 \
          --allow API-Football-auto/allowlist_ALL.txt \
          --outdir API-Football-auto/live_odds





      - name: Patch odds → Firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          LATEST=$(ls -1t API-Football-auto/live_odds/odds_full_*.json | head -n1)
          python API-Football-auto/scripts/patch_odds.py --json "$LATEST"






