# .github/workflows/daily-odds.yml
name: daily-odds

on:
  schedule:
    - cron: "*/30 6-22 * * *"   # ทุก 30 นาที ช่วงก่อนแข่ง (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # ชี้โฟลเดอร์ทำงานไปที่โปรเจกต์จริง (ตามโครงสร้างของคุณ)
    defaults:
      run:
        working-directory: winscoreai-auto-github/API-Football-auto

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # .github/workflows/daily-odds.yml (ช่วง Pull odds JSON)
      - name: Pull odds JSON
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_VENDOR: ${{ secrets.API_FOOTBALL_VENDOR }}
        run: |
          python scripts/af_today_odds.py \
          --days 2 \
          --allow allowlist_ALL.txt \
          --outdir live_odds


      - name: Patch odds → Firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          LATEST=$(ls -1t live_odds/odds_full_*.json 2>/dev/null | head -n1 || true)
          if [ -z "$LATEST" ]; then
            echo "⚠️ ไม่มีไฟล์ JSON (อาจไม่มีแมตช์ก่อนเตะวันนี้) — ข้ามการเขียน Firebase"
            exit 0
          fi
          echo "Use JSON: $LATEST"
          python scripts/patch_odds.py --json "$LATEST"

      # เก็บไฟล์ไว้ดูที่ Artifacts
      - name: Upload JSON artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odds-json
          path: live_odds/odds_full_*.json
          if-no-files-found: warn

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odds-csv
          path: live_odds/odds_flat_all_*.csv
          if-no-files-found: warn




