name: daily-runner

on:
  schedule:
    - cron: '0 2 * * *'  # 09:00 เวลาไทย
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    env:
       FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
       python-version: '3.10' 

    - name: Install dependencies
      run: pip install -r winscoreai-auto-github/requirements.txt

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python winscoreai-auto-github/daily_runner.py
